language: python

stages:
  - lint
  - test
  - build
  - coverage
  - deploy

install:
  - pip install -r test_requirements.txt
  - pip install .

script: python -m pytest

jobs:
  include:
    - stage: lint
      python: "3.7"
      before_install:
        - pip install flake8
      script:
        - flake8 lib/ tests setup.py

    - stage: test
      python: "3.6"
    - python: pypy
    - python: "3.7"
      dist: xenial

    - stage: coverage
      python: "3.7"
      before_install: python -m pip install codecov pytest-cov
      script: python -m pytest --cov
      after_success: codecov
      dist: xenial

    - stage: deploy
      script: python setup.py sdist
      deploy:
        provider: pypi
        user: j_lubcke
        password:
          secure: KUdsGDam5RYMl8G7hS7RmXURigBnktlUlMDVhzVnGVVMfbivx0Gf/Mk1N0NiithYcQQxQn4i/sR2NuHsLUlrLPngL1/4aycYHUcxsWFxu7TFhDxuPW5qljZrh9hmTQ1s10RpXc8mrZG/cMnls5/F0FYSwhNb2f48tb94ypTzQIlA1Nn1Ns4M+CduvBPne/qGBud2xjNejJx67utV3FF6CoscscWa8UWMS17PHOJzGkODIbhU0tzewmHydF2OwjTzcTI9UGSTxSUDlccF0Fh3UcVYj2WJx00XBdOoTMiFJvssFkNE4hHehxBC1CZ45AvX6GKGResHpwjw4mKMH5nbk0AmqlEumHuV2KDg3LwxgOvX5uao5agdzFnGqwzubdZuIndd5pc3Vj26j+FBMqGpWtUE3EaNuJ6t61NF7CWFS19rnhAh26Q4HzoX/Tx5hL3nag1hvBhLbK3OrEXK2I9FutmUjTKFIJ3yuMKgG0VwLti7ksNr3EYT8K/UZvhV/QAYQ03mBUigPWAW2k9x143XrUrkKbesrn0giJpOAoxZvVCNTTkzPHnfLpYNzo0D192rEZ2iGyiuVUV67+G4maPms4Je1nN81DckX3mTz2sClx+ML5nQhSZIPsHqUFl5E4rlLh8Me/fpa55qfZV04FuETt5Z8xmhxo6iu+U2HVJ4hxQ=
        on:
          tags: true
          repo: TriOptima/tri.named-struct
